
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:18-alpine
    environment:
      TZ: Europe/Prague
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "54023:5432"
    networks:
      - poker-network      
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
  database-test:
    image: postgres:18-alpine
    environment:
      TZ: Europe/Prague
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
    ports:
      - "54024:5432"
    networks:
      - poker-network      
    volumes:
      - database_data_test:/var/lib/postgresql/data:rw

###< doctrine/doctrine-bundle ###
  backend:
    build: .
    volumes:
      - .:/var/www/html
    #  - /app/var # Anonymní volume - cache a logy zůstanou v rychlé paměti Dockeru
    #  - /app/vendor # Volitelně: vendor je taky obrovský, tohle ho zrychlí
    environment:
      TZ: Europe/Prague
    networks:
      - poker-network
    depends_on:
      - database
      - database-test
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html # Nginx potřebuje přístup k public/index.php
      - ./default.conf:/etc/nginx/conf.d/default.conf # Naše konfigurace
    networks:
      - poker-network
    depends_on:
      - backend
networks:
  poker-network:
    external: true
    
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
  database_data_test:
###< doctrine/doctrine-bundle ###
