<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260425182409 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, filesize DOUBLE PRECISION NOT NULL, media_type VARCHAR(255) NOT NULL, user_id_id INT NOT NULL, tournament_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6A2CA10C9D86650F ON media (user_id_id)');
        $this->addSql('CREATE INDEX IDX_6A2CA10CBE120E4E ON media (tournament_id_id)');
        $this->addSql('CREATE TABLE participants (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, placement INT DEFAULT NULL, how_well_played VARCHAR(255) DEFAULT NULL, rebuy INT DEFAULT NULL, how_much_won INT NOT NULL, player_id_id INT NOT NULL, tournament_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_71697092C036E511 ON participants (player_id_id)');
        $this->addSql('CREATE INDEX IDX_71697092BE120E4E ON participants (tournament_id_id)');
        $this->addSql('CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, is_guest BOOLEAN NOT NULL, rating INT DEFAULT NULL, motto VARCHAR(255) DEFAULT NULL, user_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_98197A659D86650F ON player (user_id_id)');
        $this->addSql('CREATE TABLE tournament (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, is_trophy BOOLEAN NOT NULL, is_event BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, text TEXT DEFAULT NULL, send_email BOOLEAN DEFAULT NULL, buy_in INT NOT NULL, is_rebuy BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10CBE120E4E FOREIGN KEY (tournament_id_id) REFERENCES tournament (id)');
        $this->addSql('ALTER TABLE participants ADD CONSTRAINT FK_71697092C036E511 FOREIGN KEY (player_id_id) REFERENCES player (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participants ADD CONSTRAINT FK_71697092BE120E4E FOREIGN KEY (tournament_id_id) REFERENCES tournament (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A659D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10C9D86650F');
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10CBE120E4E');
        $this->addSql('ALTER TABLE participants DROP CONSTRAINT FK_71697092C036E511');
        $this->addSql('ALTER TABLE participants DROP CONSTRAINT FK_71697092BE120E4E');
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A659D86650F');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE participants');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE tournament');
        $this->addSql('DROP INDEX UNIQ_8D93D649E7927C74');
    }
}
